pkg/falco/tester.go, tests/data/data.go, tests/data/plugins/plugins.go, tests/data/rules/rules.go, tests/falco/commands_test.go, tests/falco/legacy_test.go, tests/falco/miscs_test.go
Most of the Falco tests are meant to work on a Falco installation, specially looking for a default config file (`/etc/falco/falco.yaml`). During local development, this can cause trouble when specifying a custom executable path but when the default config file cannot be found.
This PR mitigates the problem towards a better UX when running tests locally for development purposes, by skipping all tests for which a Falco binary is specified but the default config file cannot be found (only when required).
=> update(tests/falco): skip tests requiring default config if file is not present

tests/falco/commands_test.go, tests/falco/miscs_test.go, tests/tests.go
Static Falco builds can't load plugins from dynamic libraries currently, so this PR adds an option that allows skipping incompatible tests.
=> update(tests): handle falco static builds

go.mod, go.sum, pkg/run/docker.go
Upgrade docker dependency to match version required by [falcoctl](https://github.com/falcosecurity/falcoctl). 
This way both package are compatible with each other again.
Fixes #17
=> chore(run) Update docker dependency

README.md, tests/falco/legacy_test.go
After this commit in Falcosecurity/libs (https://github.com/falcosecurity/libs/commit/06289ec65d665760992772266ea993557de40d04) the behavior of `TestFalco_Legacy_RunShellUntrusted` should change.
Before this commit the rule `Run shell untrusted` was triggered with this scap-file `/traces-positive/run-shell-untrusted.scap` because this condition `proc.pname exists` was satisfied. The event number that triggered the rule was `432`. Analyzing the scap-file we can notice that the `proc.pname` associated with this event refers to an invalid thread (so a thread created by us and not really captured on the system). After the aforementioned commit invalid threads are no more considered valid parents because they carry unreliable information for this reason this rule won't trigger anymore because …
=> fix(falco/legacy_test.go): change expected detections in `TestFalco_Legacy_RunShellUntrusted`

.github/workflows/ci.yaml, tests/data/rules/legacy.go, tests/falco/legacy_test.go, tests/k8saudit/k8saudit_test.go
Legacy tests are designed to test Falco features, not the ruleset. Most of these tests already use ad-hoc rules files, not those provided by the tested Falco package. This commit also aligns the same behavior for legacy tests requiring the default rulesets. This is particularly relevant after we split `falco_rules.yaml` in multiple files, which are not shipped anymore by default.
=> fix(tests): use legacy rules files for legacy tests

tests/falco/commands_test.go
Old regex wouldn't match RC Falco releases, like: 0.36.0-rc1; see https://github.com/falcosecurity/falco/actions/runs/6146946513
New regex correctly matches by expecting either:
* none (ie: 0.36.0)
* `-$word`  like: 0.36.0-rc1
* `+$hash` like: 0.36.0+aaaaa
* development versions like: 0.36.0-198+30aa28f
See https://regex101.com/r/Cxg7oX/1
=> fix(tests): fixed for falco RCs releases.

tests/falcoctl/artifact_test.go
I believe we are hitting this race condition: https://github.com/sigstore/cosign/issues/2576
Meaning that if we disable parallel runs for those jobs this may get better. I'm not sure if the `t.Parallel()` above those functions should be removed as well.
=> fix(artifact): do not run artifact installs in parallel

pkg/falco/tester_output_describe.go, tests/data/rules/falco.go, tests/falco/commands_test.go
Follow-up to https://github.com/falcosecurity/falco/pull/2817
This also adds new types under the Falco package, as in this todo: https://github.com/falcosecurity/rules/blob/bea364ef41e78b64e6936560d12c1c14f42bd111/build/checker/cmd/compare.go#L31
=> new: add tests for rules description

tests/falco/commands_test.go
In the `TestFalco_Print_Rules/json-valid-rules` we load the `json` plugin, which we can't do in  static Falco builds. This is causing failures in bumping the submodule in mainline Falco.
=> fix(tests/falco): solve issues with description tests for static builds

tests/falco/commands_test.go
This change unblocks https://github.com/falcosecurity/falco/pull/2934. That PR makes the behavior of the description feature consistent in case of invalid rule by always returning an error. Before, we used to return an error with JSON output and an empty output with text output.
=> fix(tests/falco): invalid rule names must return error when described

tests/data/rules/falco.go, tests/falco/legacy_test.go
remove some legacy tests because now they are supported inside Falco unit tests, see https://github.com/falcosecurity/falco/pull/2992
=> cleanup(falco): remove some legacy tests

.github/workflows/ci.yaml, pkg/falco/tester_options.go, tests/falco/commands_test.go, tests/falco/miscs_test.go, tests/falcodriverloader/drivers_test.go
sync command line options with Falco 0.38.0
=> update: sync command line options with Falco 0.38.0

tests/data/configs/configs.go, tests/falco/config_test.go
add initial new test `TestFalco_Config_Metrics_Enabled` related to the metrics config.
=> new(tests/falco): add TestFalco_Config_Metrics_Enabled

action.yml
Fixup to #46 
cc @LucaGuerra 
See https://github.com/falcosecurity/falco/actions/runs/8662853602/job/23756618239?pr=3154
=> chore(action.yml): use unique name for uploaded artifact.

action.yml
See #46  that introduced the change.
cc @LucaGuerra
=> fix(action): always store outputs, even when test fails.

tests/data/rules/legacy.go, tests/falco/legacy_test.go
=> fix: add `""` case for user.name

tests/k8saudit/k8saudit_test.go
Following up commit https://github.com/falcosecurity/plugins/commit/472fd1fc531d74b05acf338db0674d41fbd6e478, released in `k8saudit-rules` v0.9.0, the k8saudit tests should be updated
=> fix(tests/k8saudit): adapt tests to rules v0.9.0

tests/falcodriverloader/drivers_test.go
/hold
until falcoctl v0.8.0-rc4 gets released
=> chore(tests/falcodriverloader): fixed up falcoctl driver loader strings for v0.8.0-rc4+

.github/workflows/ci.yaml, action.yml, pkg/falco/tester_options.go, tests/dummy/dummy_test.go, tests/dummy/generate.go, tests/falco/miscs_test.go
We have a new dep on the `dummy` plugin (that gets automatically installed by composite action), because we use it to test that prometheus metrics are not killing Falco (-> https://github.com/falcosecurity/falco/issues/3229).
We have also a new test (`TestFalco_Miscs_PrometheusMetricsNoDriver`) to test prometheus metrics in normal Falco run (in nodriver mode).
/cc @jasondellaluce @leogr
=> new(tests,pkg,action): added 2 new tests around prometheus metrics.

tests/falco/legacy_test.go
Test `TestFalco_Legacy_NonSudoSetuid` was affected by the bug reported here  https://github.com/falcosecurity/libs/pull/1923. A thread with vtid=-1 was considered as a container thread and for this reason, we didn't match the rule because of this condition `container and not user.name in ("<NA>","N/A","")`. The user is NA and before the fix, we were considered in a container.
Now with the fix, we are no longer in a container so the rule correctly triggers. Full rule output with addition of `thread.vtid` and `thread.tid`
```
22:23:30.177328055: Notice Unexpected setuid call by non-sudo, non-root program (user=<NA> tid=10397, vtid=<NA> user_loginuid=-1 cur_uid=4294967295 parent=<NA> command=<NA> pid=-1 uid=root container_id= image=<NA>)
```
=> fix: update test with latest libs fix

tests/falco/legacy_test.go
The `TestFalco_Legacy_StdoutOutputJsonStrict` was checking if the output contained specific json strings that needed to match character by character. This PR changes it so that it requires only that the json object are equivalent even if the strings are different (e.g. same properties printed in different order)
=> fix(tests/legacy): relax json string requirement

pkg/falco/tester_options.go, tests/falco/legacy_test.go
https://github.com/falcosecurity/falco/pull/3311 is dropping the deprecated `-t,-T,-D` options.
This PR removes `TestFalco_Legacy_DisabledAndEnabledRules1` and `TestFalco_Legacy_DisabledAndEnabledRules2` tests since they are no more needed.
Also, it bumps all other tests regarding rule disable/enable tags to the newly introduced in Falco 0.38 `rules:` config key: https://github.com/falcosecurity/falco/pull/3178
=> cleanup(tests/falco): remove dropped CLI options test.

tests/falco/legacy_test.go
On some arm64 runners we need a bit more time
=> fix(legacy): more detailed error and more time in legacy test

tests/falco/legacy_test.go
This test is extremely flaky on our new aarch64 nodes. Let's remove it until we have completely stabilized them, then we can add it back.
Note: we could run it selectively but honestly at this point I would simply like to disable it and reintroduce it later.
=> fix(legacy): remove gRPC flaky test

.github/workflows/ci.yaml, tests/falco/legacy_test.go
https://github.com/falcosecurity/libs/pull/2165 exposed a bug in the `TestFalco_Legacy_FalcoEventGenerator` test.
Previous code was storing full user/group info in threadinfo; before parsers understood that container_id was changed (ie: we entered a container), `set_{user,group}` was called (eg here: https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/parsers.cpp#L1769), storing in the threadinfo user and group information related to uid and gid for the host. Then, when refreshing info for the container(https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/parsers.cpp#L1843), since the container data cannot be loaded while replaying a scap file, and since the scap file itself does not container `useradded` events (being too old), we did not overwrite …
=> cleanup(tests): remove wrong/unused assert.

pkg/falco/tester_options.go
`-A` is going to be dropped in 0.41.0
/hold
=> chore(pkg/falco): use `base_syscalls.all` instead of `-A` to enable all syscalls

pkg/falco/helpers.go, tests/dummy/dummy_test.go
Add dummy InitConfig to dummy test to force init config templating logic to run.
Fix the PluginConfigInfo InitiConfig templating to use exported function and directly call it.
This fix is necessary to for example test Falco rules using this pkg when plugins such as the k8smeta plugin are required as the plugin has a few required init config fields.
The go template logic requires the the field to be exported in order to be able to render it. For unexported fields we otherwise see an error like this:
```
template: :7:27: executing "" at <$p.initConfigString>: can't evaluate field initConfigString in type *falco.PluginConfigInfo
```
Similarly it seems that for struct functions evaluating to string the template pkg seems to treat them as fields. So using the `call` keyword results in the …
=> Fix plugin config init config template
